version: "3.6"

networks:
    project_network:
        driver: bridge
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/backend
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
        - "8880:80"
    depends_on:
      - app
    container_name: project_nginx
    networks:
        - project_network
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/backend
    depends_on:
      - mysql
      - redis
    container_name: project_app
    networks:
        - project_network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: project
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    ports:
      - "8801:3306"
    command:
      - --table_definition_cache=100
      - --performance_schema=0
      - --default-authentication-plugin=mysql_native_password
      - --innodb_use_native_aio=0
    volumes:
#      - ./init:/docker-entrypoint-initdb.d
      - ./tmp/db:/var/lib/mysql
    container_name: project_mysql
    networks:
        - project_network

  redis:
      image: redis:7.0
      container_name: project_redis
      volumes:
          - ./tmp/redis:/data
      ports:
          - "8802:6379"
      networks:
          - project_network
